function(delay_link_libraries _target _scope)
    foreach(_dll ${ARGN})
        get_target_property(_path ${_dll} IMPORTED_LOCATION_RELEASE)
        if (_path STREQUAL "_path-NOTFOUND")
            get_target_property(_output ${_dll} OUTPUT_NAME)
            if (_output STREQUAL "_output-NOTFOUND")
                if (MSVC)
                    set(_name "${_dll}.dll")
                else()
                    set(_name "lib${_dll}.dll")
                endif()
            else()
                set(_name "${_output}.dll")
            endif()
        else()
            get_filename_component(_name ${_path} NAME)
        endif()
        message("delay: ${_name}")
        target_link_options(${_target} ${_scope} "/DELAYLOAD:${_name}")
    endforeach()
endfunction()
