#ifndef CHORUSKIT_PARSESVIP3GLOBAL_H
#define CHORUSKIT_PARSESVIP3GLOBAL_H

#include <QtGlobal>

#ifdef PARSESVIP3_LIBRARY
#    define PARSESVIP3_EXPORT Q_DECL_EXPORT
#else
#    define PARSESVIP3_EXPORT Q_DECL_IMPORT
#endif

#endif // CHORUSKIT_PARSESVIP3GLOBAL_H
