#ifndef IMPORTMANAGERGLOBAL_H
#define IMPORTMANAGERGLOBAL_H

#include <QtGlobal>

#if defined(IMPORTMANAGER_LIBRARY)
#    define IMPORTMANAGER_EXPORT Q_DECL_EXPORT
#else
#    define IMPORTMANAGER_EXPORT Q_DECL_IMPORT
#endif

#endif // IMPORTMANAGERGLOBAL_H
