//
// Created by Crs_1 on 2023/8/12.
//

#include <QtGlobal>

#ifndef CHORUSKIT_QSYSTEMSEMAPHOREGLOBAL_H
#define CHORUSKIT_QSYSTEMSEMAPHOREGLOBAL_H

#ifdef QSYSTEMSEMAPHOREEXTENDED_LIBRARY
#    define QSYSTEMSEMAPHOREEXTENDED_EXPORT Q_DECL_EXPORT
#else
#    define QSYSTEMSEMAPHOREEXTENDED_EXPORT Q_DECL_IMPORT
#endif

#endif // CHORUSKIT_QSYSTEMSEMAPHOREGLOBAL_H
