#ifndef CHORUSKIT_SCRIPTMGRGLOBAL_H
#define CHORUSKIT_SCRIPTMGRGLOBAL_H

#include <QtGlobal>

#ifdef SCRIPTMGR_LIBRARY
#    define SCRIPTMGR_EXPORT Q_DECL_EXPORT
#else
#    define SCRIPTMGR_EXPORT Q_DECL_IMPORT
#endif

#endif // CHORUSKIT_SCRIPTMGRGLOBAL_H
